# Generated by Django 4.2.28 on 2026-07-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_company_admin',
            field=models.BooleanField(default=False),
        ),
    ]
